version: "2"
services:
  web:
    image: fp
    ports:
      - "8888:80"
    restart: always
    environment:
      - PRODUCTION=true
      - DB_HOST=bd
      - DB_PORT=3306
      - DB_NAME=fp
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      - bd
  bd:
    image: mariadb
    environment:
      - MYSQL_DATABASE=fp
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /var/lib/mysql:/var/lib/mysql
