version: "3.4"
services:
  web:
    image: jamj2000/web:fp-resultados
    hostname: web
    container_name: fp_web
    ports:
      - "8888:80"
    restart: always
    environment:
      - PRODUCTION=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=fp
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
  db:
    image: jamj2000/db:fp-resultados
    hostname: db
    container_name: fp_db
    environment:
      - MARIADB_DATABASE=fp
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - datos:/var/lib/mysql
#    working_dir: /data

volumes:
    datos:
      name: fp_datos
