version: "3"
services:
  web:
    image: fp
    build: .
    ports:
      - "8888:80"
    restart: always
    environment:
      - PRODUCTION=true
      - DB_HOST=bd
      - DB_PORT=3306
      - DB_DATABASE=fp
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - bd
#    volumes:
#      - ./:/var/www/html
  bd:
    image: mariadb
    environment:
      - MYSQL_DATABASE=fp
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - fpdatabase:/var/lib/mysql
      - ./data:/data
    working_dir: /data

volumes:
    fpdatabase:
