version: "3"
services:
  web:
    image: jamj2000/web:fp-resultados
    ports:
      - "8888:80"
    restart: always
    environment:
      - PRODUCTION=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=fp
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
  db:
    image: jamj2000/db:fp-resultados
    hostname: db
    environment:
      - MARIADB_DATABASE=fp
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - datos:/var/lib/mysql
    working_dir: /data

volumes:
    datos:
